(function(){
'use strict';
const params=new URLSearchParams(location.search);
const EVENT_ID=params.get('event')||'event-sim-001';
const file=location.pathname.split('/').pop();
const LABELS={disaster_event_id:'Event',posko_id:'Posko',shelter_posko_id:'Shelter',item_name:'Item',expected_quantity:'Seharusnya',counted_quantity:'Terhitung',unit:'Satuan',batch_no:'Batch',expiry_date:'Expiry',status:'Status',family_code:'Kode KK',full_name:'Nama',age_group:'Usia',gender:'Gender',family_role:'Peran',title:'Judul',quantity:'Jumlah',target_location:'Lokasi Target',tender_type:'Jenis Tender',tender_id:'Tender ID',bidder_name:'Donatur',bidder_contact:'Kontak',offer_summary:'Penawaran',category:'Kategori',action_title:'Aksi',target_object:'Target',target_quantity:'Volume',target_unit:'Satuan Target',assigned_to:'PIC',priority:'Prioritas',action_plan_id:'Plan ID',progress_status:'Progress',realized_quantity:'Realisasi',realized_unit:'Satuan Realisasi',observation:'Observasi',reported_by:'Pelapor'};
function h(tag,cls,text){const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el}
function nice(key){return LABELS[key]||key.replaceAll('_',' ')}
function field(name,value,type){const l=h('label',null,nice(name));let i;if(file==='posko-logistik.html'&&name==='item_name'){i=document.createElement('select');const o=document.createElement('option');o.value=value||'';o.textContent='Pilih logistik masuk';i.appendChild(o)}else{i=document.createElement('input');i.value=value||'';if(type)i.type=type}i.name=name;l.appendChild(i);return l}
function summaryRow(label,value){const d=document.createElement('div');const s=h('span',null,label);const b=h('b',null,value||'-');d.append(s,b);return d}
function cardFor(table,r){const card=h('article','event-card');const title=r.action_title||r.title||r.full_name||r.item_name||r.offer_summary||r.id;card.appendChild(h('h4',null,title));const meta=[r.status,r.progress_status,r.category,r.unit,r.created_at&&String(r.created_at).slice(0,16)].filter(Boolean).join(' - ');card.appendChild(h('p',null,meta));const box=h('div','summary-list');if(table==='stock_opnames'){box.append(summaryRow('Posko',r.posko_id),summaryRow('Seharusnya',(r.expected_quantity||0)+' '+(r.unit||'')),summaryRow('Terhitung',(r.counted_quantity||0)+' '+(r.unit||'')),summaryRow('Selisih',String((Number(r.counted_quantity||0)-Number(r.expected_quantity||0)))),summaryRow('Batch',r.batch_no),summaryRow('Expiry',r.expiry_date))}
else if(table==='evacuee_registrations'){box.append(summaryRow('Shelter',r.shelter_posko_id),summaryRow('Kode KK',r.family_code),summaryRow('Usia',r.age_group),summaryRow('Gender',r.gender),summaryRow('Peran',r.family_role),summaryRow('Status',r.status))}
else if(table==='donation_tenders'){box.append(summaryRow('Item',r.item_name),summaryRow('Jumlah',(r.quantity||0)+' '+(r.unit||'')),summaryRow('Lokasi',r.target_location),summaryRow('Jenis',r.tender_type),summaryRow('Status',r.status))}
else if(table==='donation_bids'){box.append(summaryRow('Tender',r.tender_id),summaryRow('Donatur',r.bidder_name),summaryRow('Kontak',r.bidder_contact),summaryRow('Jumlah',(r.quantity||0)+' '+(r.unit||'')),summaryRow('Status',r.status))}
else if(table==='action_plans'){box.append(summaryRow('Kategori',r.category),summaryRow('Target',r.target_object),summaryRow('Volume',(r.target_quantity||0)+' '+(r.target_unit||'')),summaryRow('PIC',r.assigned_to),summaryRow('Prioritas',r.priority),summaryRow('Status',r.status))}
else if(table==='action_plan_updates'){box.append(summaryRow('Plan ID',r.action_plan_id),summaryRow('Progress',r.progress_status),summaryRow('Realisasi',(r.realized_quantity||0)+' '+(r.realized_unit||'')),summaryRow('Pelapor',r.reported_by),summaryRow('Observasi',r.observation))}
card.appendChild(box);return card}
function panel(title,subtitle,guide,formId,listId,fields,table,formTitle){const sec=h('section','content-grid rn-domain-p1');const left=h('div','panel');const ph=h('div','panel-header');const wrap=h('div');wrap.append(h('h3',null,title),h('p',null,subtitle));ph.appendChild(wrap);left.append(ph);const guideBox=h('div','summary-list');guide.forEach(x=>guideBox.appendChild(summaryRow(x[0],x[1])));left.appendChild(guideBox);const list=h('div','event-list');list.id=listId;left.appendChild(list);const aside=h('aside','panel summary');aside.appendChild(h('h3',null,formTitle||'Tambah Data'));const f=h('form','rn-form');f.id=formId;f.dataset.table=table;const grid=h('div','form-grid');fields.forEach(x=>grid.appendChild(field(x[0],x[1],x[2])));f.appendChild(grid);const actions=h('div','form-actions');const b=h('button','btn primary','Simpan');b.type='submit';actions.appendChild(b);const msg=h('span','form-message');msg.dataset.inlineMsg=formId;actions.appendChild(msg);f.appendChild(actions);aside.appendChild(f);sec.append(left,aside);return sec}
function mount(node){const main=document.querySelector('main.main');const grid=main&&main.querySelector('.kpi-grid');if(grid)grid.insertAdjacentElement('afterend',node);else if(main)main.appendChild(node)}
async function load(table,listId){const list=document.getElementById(listId);if(!list)return;try{const rows=await rnFetch('/dms-gap/'+table+'?disaster_event_id='+encodeURIComponent(EVENT_ID));list.innerHTML='';if(!rows.length){const empty=h('article','event-card');empty.append(h('h4',null,'Belum ada data'),h('p',null,'Isi form di kanan saat data operasional tersedia.'));list.appendChild(empty);return}rows.forEach(r=>list.appendChild(cardFor(table,r)))}catch(e){list.innerHTML='<article class= event-card><h4>API belum terbaca</h4><p>'+e.message+'</p></article>'}}
function bind(formId,listId){const f=document.getElementById(formId);if(!f)return;f.addEventListener('submit',async e=>{e.preventDefault();const data={};new FormData(f).forEach((v,k)=>{if(String(v).trim())data[k]=v});const msg=document.querySelector('[data-inline-msg="'+formId+'"]');try{if(msg)msg.textContent='Menyimpan...';await rnFetch('/dms-gap/'+f.dataset.table,{method:'POST',body:JSON.stringify(data)});if(msg)msg.textContent='Tersimpan.';await load(f.dataset.table,listId)}catch(err){if(msg)msg.textContent=err.message}})}
async function populateStockDropdown(){const f=document.getElementById('stockOpnameForm');if(!f)return;const sel=f.querySelector('select[name=item_name]');if(!sel)return;try{const offers=await rnFetch('/aid-offers');sel.innerHTML='';offers.forEach(a=>{const o=document.createElement('option');o.value=a.item_name||'';o.textContent=(a.item_name||'-')+' - '+(a.quantity||0)+' '+(a.unit||'')+' - '+(a.expiry_date||'tahan lama');o.dataset.unit=a.unit||'';o.dataset.batch=a.batch_no||'';o.dataset.expiry=a.expiry_date||'';o.dataset.qty=a.quantity||'';sel.appendChild(o)});sel.onchange=()=>{const o=sel.selectedOptions[0];if(!o)return;if(f.unit)f.unit.value=o.dataset.unit||'';if(f.batch_no)f.batch_no.value=o.dataset.batch||'';if(f.expiry_date)f.expiry_date.value=o.dataset.expiry||'';if(f.expected_quantity)f.expected_quantity.value=o.dataset.qty||f.expected_quantity.value};sel.onchange()}catch(e){console.error('stock dropdown',e)}}
function initLogistik(){const node=panel('Stock Opname & Batch Expiry','Dipakai saat operator mengecek stok fisik, nomor batch, dan expiry barang di gudang/posko.',[['Kapan dipakai','Saat stok datang, stok opname harian, atau sebelum distribusi.'],['Cara pakai','Isi jumlah seharusnya dan terhitung; selisih otomatis terlihat di kartu.'],['Migrasi Frappe','Masuk sebagai sumber P1 stock opname.']],'stockOpnameForm','stockOpnameList',[['disaster_event_id',EVENT_ID],['posko_id','posko-sim-logistik'],['item_name','Air mineral'],['expected_quantity','100','number'],['counted_quantity','96','number'],['unit','dus'],['batch_no','BATCH-001'],['expiry_date','2026-12-31'],['status','draft']],'stock_opnames','Input Stock Opname');mount(node);bind('stockOpnameForm','stockOpnameList');load('stock_opnames','stockOpnameList');populateStockDropdown()}
function initShelter(){const node=panel('Registrasi Pengungsi','Catat individu atau keluarga yang tinggal di shelter.',[['Kapan dipakai','Saat check-in pengungsi atau pembaruan data keluarga.'],['Cara pakai','Isi kode KK bila ada, nama, kelompok usia, dan status.'],['Migrasi Frappe','Masuk sebagai sumber P1 evacuee registration.']],'evacueeForm','evacueeList',[['disaster_event_id',EVENT_ID],['shelter_posko_id','posko-sim-shelter'],['family_code','KK-SIM-001'],['full_name','Nama Pengungsi'],['age_group','adult'],['gender','unknown'],['family_role','head'],['status','registered']],'evacuee_registrations','Tambah Registrasi Pengungsi');mount(node);bind('evacueeForm','evacueeList');load('evacuee_registrations','evacueeList')}
function initDonor(){const tend=panel('Tender Donasi','Buka kebutuhan donasi spesifik agar donor bisa merespons jelas.',[['Kapan dipakai','Saat posko perlu membuka permintaan bantuan yang bisa dipenuhi donor.'],['Cara pakai','Isi item, jumlah, lokasi target, dan status open.'],['Migrasi Frappe','Masuk sebagai sumber P1 donation tender.']],'tenderForm','tenderList',[['disaster_event_id',EVENT_ID],['title','Kebutuhan tenda keluarga'],['item_name','Tenda keluarga'],['quantity','20','number'],['unit','unit'],['target_location','Shelter utama'],['tender_type','donation_request'],['status','open']],'donation_tenders','Tambah Tender Donasi');const bid=panel('Bid / Penawaran Donatur','Catat respons donor terhadap tender atau kebutuhan terbuka.',[['Kapan dipakai','Saat donor menawarkan barang/jasa untuk kebutuhan tertentu.'],['Cara pakai','Isi nama donor, kontak, ringkasan tawaran, jumlah, dan status.'],['Migrasi Frappe','Masuk sebagai sumber P1 donation bid.']],'bidForm','bidList',[['disaster_event_id',EVENT_ID],['tender_id',''],['bidder_name','Donor Simulasi'],['bidder_contact','0800000000'],['offer_summary','Siap kirim bantuan'],['quantity','5','number'],['unit','unit'],['status','submitted']],'donation_bids','Tambah Penawaran Donatur');mount(tend);tend.insertAdjacentElement('afterend',bid);bind('tenderForm','tenderList');bind('bidForm','bidList');load('donation_tenders','tenderList');load('donation_bids','bidList')}
document.addEventListener('DOMContentLoaded',()=>{if(file==='posko-logistik.html')initLogistik();if(file==='shelter-detail.html')initShelter();if(file==='donor-program.html')initDonor();});
})();
